//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lockscreen_Swap {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lockscreen_Swap.AppResx", typeof(AppResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lock screen.
        /// </summary>
        public static string AAA_1 {
            get {
                return ResourceManager.GetString("AAA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallpaper.
        /// </summary>
        public static string AAA_2 {
            get {
                return ResourceManager.GetString("AAA_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to battery.
        /// </summary>
        public static string AAA_3 {
            get {
                return ResourceManager.GetString("AAA_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.
        /// </summary>
        public static string AAA_4 {
            get {
                return ResourceManager.GetString("AAA_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture.
        /// </summary>
        public static string AAA_5 {
            get {
                return ResourceManager.GetString("AAA_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this application to create changing wallpapers.
        ///In addition, the application allows to display information about the status of your battery.
        ///Lots of great settings are ready for this.
        ///Your background image and your battery indicator is updated every 30 minutes.
        ///
        ///All new!
        ///Update GRD3 the application issues spoken notifications..
        /// </summary>
        public static string AAA_AppDescription {
            get {
                return ResourceManager.GetString("AAA_AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 Screen changer.
        /// </summary>
        public static string AAA_AppName {
            get {
                return ResourceManager.GetString("AAA_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all pictures.
        /// </summary>
        public static string AllPictures {
            get {
                return ResourceManager.GetString("AllPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery fully charged.
        /// </summary>
        public static string BatteryFullyCharged {
            get {
                return ResourceManager.GetString("BatteryFullyCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery is charging.
        /// </summary>
        public static string BatteryIsCharging {
            get {
                return ResourceManager.GetString("BatteryIsCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery low.
        /// </summary>
        public static string BatteryLow {
            get {
                return ResourceManager.GetString("BatteryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery status.
        /// </summary>
        public static string BatteryStatus {
            get {
                return ResourceManager.GetString("BatteryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy this app.
        /// </summary>
        public static string BuyApp {
            get {
                return ResourceManager.GetString("BuyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click screen to skip.
        /// </summary>
        public static string ClickSkip {
            get {
                return ResourceManager.GetString("ClickSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy folder.
        /// </summary>
        public static string CopyFolder {
            get {
                return ResourceManager.GetString("CopyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy pictures to.
        /// </summary>
        public static string CopyImagesTo {
            get {
                return ResourceManager.GetString("CopyImagesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy pictures.
        /// </summary>
        public static string CopyPictures {
            get {
                return ResourceManager.GetString("CopyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        public static string CreateNewFolder {
            get {
                return ResourceManager.GetString("CreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatically.
        /// </summary>
        public static string CutAuto {
            get {
                return ResourceManager.GetString("CutAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut picture.
        /// </summary>
        public static string CutPicture {
            get {
                return ResourceManager.GetString("CutPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut pictures.
        /// </summary>
        public static string CutPictures {
            get {
                return ResourceManager.GetString("CutPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DeleteBar {
            get {
                return ResourceManager.GetString("DeleteBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete pictures.
        /// </summary>
        public static string DeleteImages {
            get {
                return ResourceManager.GetString("DeleteImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Enter name!.
        /// </summary>
        public static string ErrorEnterName {
            get {
                return ResourceManager.GetString("ErrorEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Enter new name!.
        /// </summary>
        public static string ErrorEnterNewName {
            get {
                return ResourceManager.GetString("ErrorEnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Name already in use or invalid characters!.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Background agents for this application have been disabled by the user!.
        /// </summary>
        public static string ExError {
            get {
                return ResourceManager.GetString("ExError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new.
        /// </summary>
        public static string GenerateNew {
            get {
                return ResourceManager.GetString("GenerateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string InstGeneralHeader {
            get {
                return ResourceManager.GetString("InstGeneralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this application to create changing wallpapers. In addition, the application allows to display information about the status of your battery.
        ///To do this, lots of settings are available. Your background image and your battery indicator is updated every 30 minutes. Please note that Windows phone to the run background services requires an active Internet connection.
        ///The display on the lock screen is based on the Windows phone notification system. It is therefore only a maximum display 99% possible..
        /// </summary>
        public static string InstGeneralText {
            get {
                return ResourceManager.GetString("InstGeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string InstMiscellaneousHeader {
            get {
                return ResourceManager.GetString("InstMiscellaneousHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate good this application if you like. If you have problems with this application, then please contact support! Questions and issues have lost nothing in the reviews.
        ///Thank you very much!.
        /// </summary>
        public static string InstMiscellaneousText {
            get {
                return ResourceManager.GetString("InstMiscellaneousText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string InstPictureHeader {
            get {
                return ResourceManager.GetString("InstPictureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a folder, open it and import, as many images. When the import of images each image can be aligned and cut. The image is always created in the maximum resolution for your mobile phone. You can create multiple folders to quickly switch your background images..
        /// </summary>
        public static string InstPictureText {
            get {
                return ResourceManager.GetString("InstPictureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string InstSettingsHeader {
            get {
                return ResourceManager.GetString("InstSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background and the battery status indicator can be adjusted on the settings page. Select a folder from the changing images are loaded. You can also choose whether the images of the series should be loaded to or one will be chosen at random.
        ///The battery status indicator must be set in the system preferences. A link for this purpose is available in the application&apos;s settings.
        ///In addition, you can choose notification sounds. That sounds special alerts are spoken. Please note that this and silent notifica [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InstSettingsText {
            get {
                return ResourceManager.GetString("InstSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like xtrose.
        /// </summary>
        public static string LikeXtrose {
            get {
                return ResourceManager.GetString("LikeXtrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You said no, so I can&apos;t update your background..
        /// </summary>
        public static string LockhelperInfo {
            get {
                return ResourceManager.GetString("LockhelperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen changer.
        /// </summary>
        public static string LockScreenChanger {
            get {
                return ResourceManager.GetString("LockScreenChanger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen settings.
        /// </summary>
        public static string LockScreenSettings {
            get {
                return ResourceManager.GetString("LockScreenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low battery  warning.
        /// </summary>
        public static string LowBatteryWarning {
            get {
                return ResourceManager.GetString("LowBatteryWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no picture in selected folder. Open folder and import pictures..
        /// </summary>
        public static string MsgNoPicture {
            get {
                return ResourceManager.GetString("MsgNoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to multiple add.
        /// </summary>
        public static string MultipleAdd {
            get {
                return ResourceManager.GetString("MultipleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string NoteLanguage {
            get {
                return ResourceManager.GetString("NoteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application.
        /// </summary>
        public static string NoteLanguage2 {
            get {
                return ResourceManager.GetString("NoteLanguage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification fully charged.
        /// </summary>
        public static string NotificationFullyCharged {
            get {
                return ResourceManager.GetString("NotificationFullyCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification is charging.
        /// </summary>
        public static string NotificationIsCharging {
            get {
                return ResourceManager.GetString("NotificationIsCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification sounds.
        /// </summary>
        public static string NotificationSounds {
            get {
                return ResourceManager.GetString("NotificationSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other xtrose apps.
        /// </summary>
        public static string OtherApps {
            get {
                return ResourceManager.GetString("OtherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sounds.
        /// </summary>
        public static string PlaySounds {
            get {
                return ResourceManager.GetString("PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait......
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing this app.
        /// </summary>
        public static string PurchaseNote {
            get {
                return ResourceManager.GetString("PurchaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to random.
        /// </summary>
        public static string Random {
            get {
                return ResourceManager.GetString("Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random folder.
        /// </summary>
        public static string RandomFolder {
            get {
                return ResourceManager.GetString("RandomFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string Randomization {
            get {
                return ResourceManager.GetString("Randomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random picture.
        /// </summary>
        public static string RandomPicture {
            get {
                return ResourceManager.GetString("RandomPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename folder.
        /// </summary>
        public static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate left.
        /// </summary>
        public static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rotate right.
        /// </summary>
        public static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved pictures.
        /// </summary>
        public static string SavedPictures {
            get {
                return ResourceManager.GetString("SavedPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pictures to copy.
        /// </summary>
        public static string SelectCopy {
            get {
                return ResourceManager.GetString("SelectCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select pictures to delete.
        /// </summary>
        public static string SelectDelete {
            get {
                return ResourceManager.GetString("SelectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the pictures to the Add.
        /// </summary>
        public static string SelectImages {
            get {
                return ResourceManager.GetString("SelectImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single add.
        /// </summary>
        public static string SingleAdd {
            get {
                return ResourceManager.GetString("SingleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target are the same.
        /// </summary>
        public static string SourceTarget {
            get {
                return ResourceManager.GetString("SourceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special.
        /// </summary>
        public static string Special {
            get {
                return ResourceManager.GetString("Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard.
        /// </summary>
        public static string Standard {
            get {
                return ResourceManager.GetString("Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change lock screen.
        /// </summary>
        public static string TaskInfo {
            get {
                return ResourceManager.GetString("TaskInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading.
        /// </summary>
        public static string ThankYouDown {
            get {
                return ResourceManager.GetString("ThankYouDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version Expired!.
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version Expired! To create apps will cost a lot of time. The price for this work is not expensive. To continue create lock screens Images, you must buy the app. Thank you!.
        /// </summary>
        public static string TrialNote {
            get {
                return ResourceManager.GetString("TrialNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version.
        /// </summary>
        public static string TrialVersion {
            get {
                return ResourceManager.GetString("TrialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselect all.
        /// </summary>
        public static string UnselectAll {
            get {
                return ResourceManager.GetString("UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact adress.
        /// </summary>
        public static string Z01_Address {
            get {
                return ResourceManager.GetString("Z01_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batterie fully charged.
        /// </summary>
        public static string Z01_BatteryFullyCharged {
            get {
                return ResourceManager.GetString("Z01_BatteryFullyCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery is charging.
        /// </summary>
        public static string Z01_BatteryIsCharging {
            get {
                return ResourceManager.GetString("Z01_BatteryIsCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery low.
        /// </summary>
        public static string Z01_BatteryLow {
            get {
                return ResourceManager.GetString("Z01_BatteryLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Z01_Change {
            get {
                return ResourceManager.GetString("Z01_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sound set.
        /// </summary>
        public static string Z01_CompNewSound {
            get {
                return ResourceManager.GetString("Z01_CompNewSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string Z01_Components {
            get {
                return ResourceManager.GetString("Z01_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with xtrose.
        /// </summary>
        public static string Z01_Connecting {
            get {
                return ResourceManager.GetString("Z01_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting......
        /// </summary>
        public static string Z01_ConnectingNow {
            get {
                return ResourceManager.GetString("Z01_ConnectingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Z01_ConnectionFailed {
            get {
                return ResourceManager.GetString("Z01_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time out.
        /// </summary>
        public static string Z01_ConnectionTimeOut {
            get {
                return ResourceManager.GetString("Z01_ConnectionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Z01_Contact {
            get {
                return ResourceManager.GetString("Z01_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy sounds and edit it with the sounds editor.
        /// </summary>
        public static string Z01_CopySoundInfo {
            get {
                return ResourceManager.GetString("Z01_CopySoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy sounds.
        /// </summary>
        public static string Z01_CopySounds {
            get {
                return ResourceManager.GetString("Z01_CopySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new sound set.
        /// </summary>
        public static string Z01_CreateSounds {
            get {
                return ResourceManager.GetString("Z01_CreateSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option creates an sounds images set. You can edit your new sounds set with the editor..
        /// </summary>
        public static string Z01_CreateSoundsInfo {
            get {
                return ResourceManager.GetString("Z01_CreateSoundsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sounds.
        /// </summary>
        public static string Z01_DeleteSounds {
            get {
                return ResourceManager.GetString("Z01_DeleteSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading sound.
        /// </summary>
        public static string Z01_DownloadingSound {
            get {
                return ResourceManager.GetString("Z01_DownloadingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sounds.
        /// </summary>
        public static string Z01_EditSounds {
            get {
                return ResourceManager.GetString("Z01_EditSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter url from .mp3 file.
        /// </summary>
        public static string Z01_EnterUrl {
            get {
                return ResourceManager.GetString("Z01_EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR!.
        /// </summary>
        public static string Z01_Error {
            get {
                return ResourceManager.GetString("Z01_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is a system component and cannot be edited, renamed or deleted..
        /// </summary>
        public static string Z01_ErrorSounds {
            get {
                return ResourceManager.GetString("Z01_ErrorSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installed.
        /// </summary>
        public static string Z01_Installed {
            get {
                return ResourceManager.GetString("Z01_Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification sounds.
        /// </summary>
        public static string Z01_InstNoteHeader {
            get {
                return ResourceManager.GetString("Z01_InstNoteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom notification sounds are first issued higher than 8.0.10492 from an operating system version..
        /// </summary>
        public static string Z01_InstNoteText {
            get {
                return ResourceManager.GetString("Z01_InstNoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Name in use or invalid characters..
        /// </summary>
        public static string Z01_InUse {
            get {
                return ResourceManager.GetString("Z01_InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show logo on start.
        /// </summary>
        public static string Z01_LogoStart {
            get {
                return ResourceManager.GetString("Z01_LogoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string Z01_NewName {
            get {
                return ResourceManager.GetString("Z01_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No components online.
        /// </summary>
        public static string Z01_NoComponentsOnline {
            get {
                return ResourceManager.GetString("Z01_NoComponentsOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete the notification sounds really.
        /// </summary>
        public static string Z01_NoteDeleteSound {
            get {
                return ResourceManager.GetString("Z01_NoteDeleteSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification sounds.
        /// </summary>
        public static string Z01_NoteSounds {
            get {
                return ResourceManager.GetString("Z01_NoteSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string Z01_Online {
            get {
                return ResourceManager.GetString("Z01_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other xtrose apps.
        /// </summary>
        public static string Z01_OtherApps {
            get {
                return ResourceManager.GetString("Z01_OtherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Z01_Play {
            get {
                return ResourceManager.GetString("Z01_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! If sounds is set in settings, notification sounds will not work after renaming..
        /// </summary>
        public static string Z01_RenameSoundsWarning {
            get {
                return ResourceManager.GetString("Z01_RenameSoundsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename sounds.
        /// </summary>
        public static string Z01_ReneameSounds {
            get {
                return ResourceManager.GetString("Z01_ReneameSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Z01_Save {
            get {
                return ResourceManager.GetString("Z01_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is unfortunately no way to import notification tones from the phone to the app. Therefore, it must be downloaded from the Internet..
        /// </summary>
        public static string Z01_SoundChangeInfo {
            get {
                return ResourceManager.GetString("Z01_SoundChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (silent).
        /// </summary>
        public static string Z01_SoundSilent {
            get {
                return ResourceManager.GetString("Z01_SoundSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (standard).
        /// </summary>
        public static string Z01_SoundStandard {
            get {
                return ResourceManager.GetString("Z01_SoundStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!.
        /// </summary>
        public static string Z01_Warning {
            get {
                return ResourceManager.GetString("Z01_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other xtrose apps.
        /// </summary>
        public static string Z02_OtherXtroseApps {
            get {
                return ResourceManager.GetString("Z02_OtherXtroseApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Z02_RateLater {
            get {
                return ResourceManager.GetString("Z02_RateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Z02_RateNever {
            get {
                return ResourceManager.GetString("Z02_RateNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Z02_RateNow {
            get {
                return ResourceManager.GetString("Z02_RateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application seems to appeal to you.
        ///To program apps is time consuming and difficult.
        ///A good review can help us to spread it further.
        ///
        ///Thank you very much.
        /// </summary>
        public static string Z02_RateText {
            get {
                return ResourceManager.GetString("Z02_RateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.0 Screen Changer.
        /// </summary>
        public static string Z03_10_0_Screen_Changer {
            get {
                return ResourceManager.GetString("Z03_10_0_Screen_Changer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have developed a completely new app!.
        /// </summary>
        public static string Z03_T1 {
            get {
                return ResourceManager.GetString("Z03_T1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adapted to Windows 10..
        /// </summary>
        public static string Z03_T2 {
            get {
                return ResourceManager.GetString("Z03_T2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Higher resolution. Adapted to the display size..
        /// </summary>
        public static string Z03_T3 {
            get {
                return ResourceManager.GetString("Z03_T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field for user informations..
        /// </summary>
        public static string Z03_T6 {
            get {
                return ResourceManager.GetString("Z03_T6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test now.
        /// </summary>
        public static string Z03_TestNow {
            get {
                return ResourceManager.GetString("Z03_TestNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many more opportunities..
        /// </summary>
        public static string Z05_T7 {
            get {
                return ResourceManager.GetString("Z05_T7", resourceCulture);
            }
        }
    }
}
